### ISSUE TITLE
Symphony/Process required version

### ISSUE THREAD

**Issue by ockam** [NinoSkopac/PhpTikaWrapper#1]
I’m using your package with Laravel 4 which already load Symphony/Process 2.3.*

I’m unable to load your package through composer because you require "symfony/process": "2.1.*"

I installed it manually and it seems to work fine with 2.3. So may I suggest you change the require line to:

"symfony/process": "~2.1" (Next Significant Release)

http://getcomposer.org/doc/01-basic-usage.md#the-require-key

Thank you for making this available! It saved me a lot of work.

**Comment by fahadonline** [comment]
@NinoSkopac 

I am having similar issue with Laravel 5.3.

Any clue how can I fix it.

Below is the compose output when I try to run `composer require enzim/tika-wrapper`

`sudo composer require enzim/tika-wrapper
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.0 for enzim/tika-wrapper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install enzim/tika-wrapper 1.0.4
    - Conclusion: don't install enzim/tika-wrapper 1.0.3
    - Conclusion: don't install enzim/tika-wrapper 1.0.2
    - Conclusion: don't install enzim/tika-wrapper 1.0.1
    - Conclusion: remove symfony/process v3.1.10
    - Installation request for enzim/tika-wrapper ^1.0 -> satisfiable by enzim/tika-wrapper[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - Conclusion: don't install symfony/process v3.1.10
    - enzim/tika-wrapper 1.0 requires symfony/process ~2.1 -> satisfiable by symfony/process[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/process[v2.1.0, v3.1.10].
    - Can only install one of: symfony/process[v2.1.1, v3.1.10].
    - Can only install one of: symfony/process[v2.1.10, v3.1.10].
    - Can only install one of: symfony/process[v2.1.11, v3.1.10].
    - Can only install one of: symfony/process[v2.1.12, v3.1.10].
    - Can only install one of: symfony/process[v2.1.13, v3.1.10].
    - Can only install one of: symfony/process[v2.1.2, v3.1.10].
    - Can only install one of: symfony/process[v2.1.3, v3.1.10].
    - Can only install one of: symfony/process[v2.1.4, v3.1.10].
    - Can only install one of: symfony/process[v2.1.5, v3.1.10].
    - Can only install one of: symfony/process[v2.1.6, v3.1.10].
    - Can only install one of: symfony/process[v2.1.7, v3.1.10].
    - Can only install one of: symfony/process[v2.1.8, v3.1.10].
    - Can only install one of: symfony/process[v2.1.9, v3.1.10].
    - Can only install one of: symfony/process[v2.2.0, v3.1.10].
    - Can only install one of: symfony/process[v2.2.1, v3.1.10].
    - Can only install one of: symfony/process[v2.2.10, v3.1.10].
    - Can only install one of: symfony/process[v2.2.11, v3.1.10].
    - Can only install one of: symfony/process[v2.2.2, v3.1.10].
    - Can only install one of: symfony/process[v2.2.3, v3.1.10].
    - Can only install one of: symfony/process[v2.2.4, v3.1.10].
    - Can only install one of: symfony/process[v2.2.5, v3.1.10].
    - Can only install one of: symfony/process[v2.2.6, v3.1.10].
    - Can only install one of: symfony/process[v2.2.7, v3.1.10].
    - Can only install one of: symfony/process[v2.2.8, v3.1.10].
    - Can only install one of: symfony/process[v2.2.9, v3.1.10].
    - Can only install one of: symfony/process[v2.3.0, v3.1.10].
    - Can only install one of: symfony/process[v2.3.1, v3.1.10].
    - Can only install one of: symfony/process[v2.3.10, v3.1.10].
    - Can only install one of: symfony/process[v2.3.11, v3.1.10].
    - Can only install one of: symfony/process[v2.3.12, v3.1.10].
    - Can only install one of: symfony/process[v2.3.13, v3.1.10].
    - Can only install one of: symfony/process[v2.3.14, v3.1.10].
    - Can only install one of: symfony/process[v2.3.15, v3.1.10].
    - Can only install one of: symfony/process[v2.3.16, v3.1.10].
    - Can only install one of: symfony/process[v2.3.17, v3.1.10].
    - Can only install one of: symfony/process[v2.3.18, v3.1.10].
    - Can only install one of: symfony/process[v2.3.19, v3.1.10].
    - Can only install one of: symfony/process[v2.3.2, v3.1.10].
    - Can only install one of: symfony/process[v2.3.20, v3.1.10].
    - Can only install one of: symfony/process[v2.3.21, v3.1.10].
    - Can only install one of: symfony/process[v2.3.22, v3.1.10].
    - Can only install one of: symfony/process[v2.3.23, v3.1.10].
    - Can only install one of: symfony/process[v2.3.24, v3.1.10].
    - Can only install one of: symfony/process[v2.3.25, v3.1.10].
    - Can only install one of: symfony/process[v2.3.26, v3.1.10].
    - Can only install one of: symfony/process[v2.3.27, v3.1.10].
    - Can only install one of: symfony/process[v2.3.28, v3.1.10].
    - Can only install one of: symfony/process[v2.3.29, v3.1.10].
    - Can only install one of: symfony/process[v2.3.3, v3.1.10].
    - Can only install one of: symfony/process[v2.3.30, v3.1.10].
    - Can only install one of: symfony/process[v2.3.31, v3.1.10].
    - Can only install one of: symfony/process[v2.3.32, v3.1.10].
    - Can only install one of: symfony/process[v2.3.33, v3.1.10].
    - Can only install one of: symfony/process[v2.3.34, v3.1.10].
    - Can only install one of: symfony/process[v2.3.35, v3.1.10].
    - Can only install one of: symfony/process[v2.3.36, v3.1.10].
    - Can only install one of: symfony/process[v2.3.37, v3.1.10].
    - Can only install one of: symfony/process[v2.3.38, v3.1.10].
    - Can only install one of: symfony/process[v2.3.39, v3.1.10].
    - Can only install one of: symfony/process[v2.3.4, v3.1.10].
    - Can only install one of: symfony/process[v2.3.40, v3.1.10].
    - Can only install one of: symfony/process[v2.3.41, v3.1.10].
    - Can only install one of: symfony/process[v2.3.42, v3.1.10].
    - Can only install one of: symfony/process[v2.3.5, v3.1.10].
    - Can only install one of: symfony/process[v2.3.6, v3.1.10].
    - Can only install one of: symfony/process[v2.3.7, v3.1.10].
    - Can only install one of: symfony/process[v2.3.8, v3.1.10].
    - Can only install one of: symfony/process[v2.3.9, v3.1.10].
    - Can only install one of: symfony/process[v2.4.0, v3.1.10].
    - Can only install one of: symfony/process[v2.4.1, v3.1.10].
    - Can only install one of: symfony/process[v2.4.10, v3.1.10].
    - Can only install one of: symfony/process[v2.4.2, v3.1.10].
    - Can only install one of: symfony/process[v2.4.3, v3.1.10].
    - Can only install one of: symfony/process[v2.4.4, v3.1.10].
    - Can only install one of: symfony/process[v2.4.5, v3.1.10].
    - Can only install one of: symfony/process[v2.4.6, v3.1.10].
    - Can only install one of: symfony/process[v2.4.7, v3.1.10].
    - Can only install one of: symfony/process[v2.4.8, v3.1.10].
    - Can only install one of: symfony/process[v2.4.9, v3.1.10].
    - Can only install one of: symfony/process[v2.5.0, v3.1.10].
    - Can only install one of: symfony/process[v2.5.1, v3.1.10].
    - Can only install one of: symfony/process[v2.5.10, v3.1.10].
    - Can only install one of: symfony/process[v2.5.11, v3.1.10].
    - Can only install one of: symfony/process[v2.5.12, v3.1.10].
    - Can only install one of: symfony/process[v2.5.2, v3.1.10].
    - Can only install one of: symfony/process[v2.5.3, v3.1.10].
    - Can only install one of: symfony/process[v2.5.4, v3.1.10].
    - Can only install one of: symfony/process[v2.5.5, v3.1.10].
    - Can only install one of: symfony/process[v2.5.6, v3.1.10].
    - Can only install one of: symfony/process[v2.5.7, v3.1.10].
    - Can only install one of: symfony/process[v2.5.8, v3.1.10].
    - Can only install one of: symfony/process[v2.5.9, v3.1.10].
    - Can only install one of: symfony/process[v2.6.0, v3.1.10].
    - Can only install one of: symfony/process[v2.6.1, v3.1.10].
    - Can only install one of: symfony/process[v2.6.10, v3.1.10].
    - Can only install one of: symfony/process[v2.6.11, v3.1.10].
    - Can only install one of: symfony/process[v2.6.12, v3.1.10].
    - Can only install one of: symfony/process[v2.6.13, v3.1.10].
    - Can only install one of: symfony/process[v2.6.2, v3.1.10].
    - Can only install one of: symfony/process[v2.6.3, v3.1.10].
    - Can only install one of: symfony/process[v2.6.4, v3.1.10].
    - Can only install one of: symfony/process[v2.6.5, v3.1.10].
    - Can only install one of: symfony/process[v2.6.6, v3.1.10].
    - Can only install one of: symfony/process[v2.6.7, v3.1.10].
    - Can only install one of: symfony/process[v2.6.8, v3.1.10].
    - Can only install one of: symfony/process[v2.6.9, v3.1.10].
    - Can only install one of: symfony/process[v2.7.0, v3.1.10].
    - Can only install one of: symfony/process[v2.7.1, v3.1.10].
    - Can only install one of: symfony/process[v2.7.10, v3.1.10].
    - Can only install one of: symfony/process[v2.7.11, v3.1.10].
    - Can only install one of: symfony/process[v2.7.12, v3.1.10].
    - Can only install one of: symfony/process[v2.7.13, v3.1.10].
    - Can only install one of: symfony/process[v2.7.14, v3.1.10].
    - Can only install one of: symfony/process[v2.7.15, v3.1.10].
    - Can only install one of: symfony/process[v2.7.16, v3.1.10].
    - Can only install one of: symfony/process[v2.7.17, v3.1.10].
    - Can only install one of: symfony/process[v2.7.18, v3.1.10].
    - Can only install one of: symfony/process[v2.7.19, v3.1.10].
    - Can only install one of: symfony/process[v2.7.2, v3.1.10].
    - Can only install one of: symfony/process[v2.7.20, v3.1.10].
    - Can only install one of: symfony/process[v2.7.21, v3.1.10].
    - Can only install one of: symfony/process[v2.7.22, v3.1.10].
    - Can only install one of: symfony/process[v2.7.23, v3.1.10].
    - Can only install one of: symfony/process[v2.7.24, v3.1.10].
    - Can only install one of: symfony/process[v2.7.25, v3.1.10].
    - Can only install one of: symfony/process[v2.7.26, v3.1.10].
    - Can only install one of: symfony/process[v2.7.27, v3.1.10].
    - Can only install one of: symfony/process[v2.7.28, v3.1.10].
    - Can only install one of: symfony/process[v2.7.29, v3.1.10].
    - Can only install one of: symfony/process[v2.7.3, v3.1.10].
    - Can only install one of: symfony/process[v2.7.30, v3.1.10].
    - Can only install one of: symfony/process[v2.7.31, v3.1.10].
    - Can only install one of: symfony/process[v2.7.4, v3.1.10].
    - Can only install one of: symfony/process[v2.7.5, v3.1.10].
    - Can only install one of: symfony/process[v2.7.6, v3.1.10].
    - Can only install one of: symfony/process[v2.7.7, v3.1.10].
    - Can only install one of: symfony/process[v2.7.8, v3.1.10].
    - Can only install one of: symfony/process[v2.7.9, v3.1.10].
    - Can only install one of: symfony/process[v2.8.0, v3.1.10].
    - Can only install one of: symfony/process[v2.8.1, v3.1.10].
    - Can only install one of: symfony/process[v2.8.10, v3.1.10].
    - Can only install one of: symfony/process[v2.8.11, v3.1.10].
    - Can only install one of: symfony/process[v2.8.12, v3.1.10].
    - Can only install one of: symfony/process[v2.8.13, v3.1.10].
    - Can only install one of: symfony/process[v2.8.14, v3.1.10].
    - Can only install one of: symfony/process[v2.8.15, v3.1.10].
    - Can only install one of: symfony/process[v2.8.16, v3.1.10].
    - Can only install one of: symfony/process[v2.8.17, v3.1.10].
    - Can only install one of: symfony/process[v2.8.18, v3.1.10].
    - Can only install one of: symfony/process[v2.8.19, v3.1.10].
    - Can only install one of: symfony/process[v2.8.2, v3.1.10].
    - Can only install one of: symfony/process[v2.8.20, v3.1.10].
    - Can only install one of: symfony/process[v2.8.21, v3.1.10].
    - Can only install one of: symfony/process[v2.8.22, v3.1.10].
    - Can only install one of: symfony/process[v2.8.23, v3.1.10].
    - Can only install one of: symfony/process[v2.8.24, v3.1.10].
    - Can only install one of: symfony/process[v2.8.3, v3.1.10].
    - Can only install one of: symfony/process[v2.8.4, v3.1.10].
    - Can only install one of: symfony/process[v2.8.5, v3.1.10].
    - Can only install one of: symfony/process[v2.8.6, v3.1.10].
    - Can only install one of: symfony/process[v2.8.7, v3.1.10].
    - Can only install one of: symfony/process[v2.8.8, v3.1.10].
    - Can only install one of: symfony/process[v2.8.9, v3.1.10].
    - Installation request for symfony/process (locked at v3.1.10) -> satisfiable by symfony/process[v3.1.10].


Installation failed, reverting ./composer.json to its original content.
`

**Comment by youngbobby** [comment]
Sorry to bump this issue @ockam. Would you please share how you were able to install this manually on Laravel ? I'm currently having this issue.

Thanks.

**Comment by ockam** [comment]
@youngbobby if I remember correctly, I litterally dropped the library folder in my vendor dir, then I manually set the autoload in composer.json:
```
"autoload": {
		"classmap": [],
		"psr-0": {
			"Enzim\\Lib\\TikaWrapper\\": "vendor/enzim/tika-wrapper/TikaApp"
               }
	},
```
![Screen Shot 2019-10-10 at 08 22 47](https://user-images.githubusercontent.com/229621/66568306-2e0f6400-eb37-11e9-9fef-45e22931edeb.png)
