### ISSUE TITLE
Transfer ownership: anyone interested?

### ISSUE THREAD

**Issue by pierroweb** [NinoSkopac/PhpTikaWrapper#11]
I would like to transfer ownership of the repo as I don't have time to take care of it anymore.

Anyone would be interested?

**Comment by NinoSkopac** [comment]
Yeah man, I can do it. I'll be able to handle the pending issues quickly.

**Comment by NinoSkopac** [comment]
Here's what I'd do:

- handle the current issues 
- make a release
- prepare for a new release by compiling the latest version of tika, running examples, and so on

**Comment by pierroweb** [comment]
That's a true Christmas gift! I will study how to set up the transfer today.
Thank you Nino!

**Comment by pierroweb** [comment]
https://help.github.com/articles/about-repository-transfers/ mentions that 
> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL.

So hopefully nothing should break.
