### ISSUE TITLE
PhpTikaWrapper (Issues on server)

### ISSUE THREAD

**Issue by rhashish44** [NinoSkopac/PhpTikaWrapper#12]
Hi
I have Installed Composer on our server path /opt/cpanel/composer/bin/composer
and after that i have downloaded PhpTikaWrapper from https://github.com/pierroweb/PhpTikaWrapper  and upload folder on server after that i have installed composer phar under the PhpTikaWrapper (Same process that given https://github.com/pierroweb/PhpTikaWrapper) and i got "autoload.php" under the Vendor folder, but when i directally run on browser "PhpTikaWrapper/example/with-composer/usage.php" its not giving response. I have also change and check path of "require 'vendor/autoload.php' but its not giving response.

I seems TikaWrapper class not working  print_r(TikaWrapper::getMetaData($testFile));

Please suggest me where is mistake at my end.

**Comment by NinoSkopac** [comment]
Can I see some code, so I can try to reproduce?
