### ISSUE TITLE
English words are reversed when extracting an Arabic pdf 

### ISSUE THREAD

**Issue by sajadk** [NinoSkopac/PhpTikaWrapper#16]
This is how this pdf is extacted
[181 copy.pdf](https://github.com/NinoSkopac/PhpTikaWrapper/files/2020203/181.copy.pdf)

)740(- تعلن إدارة الع مات التجارية عن تقدم وكيل التسجيل / المالك : ا مارات لخدمات الملكية الفكرية )541(- بطلب لتسجيل بيانات الع مة التجارية : YKSA )219(- المودعة بالرقم : 112313 بتاريخ : 2008/05/07
بيانات ا ولوية :
)730(- بإسم : ش. سوسيتي دي بروموشون دي أوني كومباني آرييني ريجيونال ( سبكار )
وعنوانة : بولفارد دو 13 جانفيير (إميوبل بيدك-سيديو) بي.بي. 2988. لومي (توغو).

The 'YSKA' should be ASKY and the brackets should be like -(740) ......

What can I do to correct it ?

**Comment by sajadk** [comment]
why this issue is closed, without resolving the issue ?

**Comment by NinoSkopac** [comment]
because it’s not a relevant issue tracker, try TIKA’s tracker.
