### ISSUE TITLE
Problem with UTF-8 filenames

### ISSUE THREAD

**Issue by Abelkrown** [NinoSkopac/PhpTikaWrapper#20]
I try to get text from file with russian name like "Тест.docx" and get error:
`Exception in thread "main" java.net.MalformedURLException: no protocol: /.../web/????.docx
at java.net.URL.<init>(URL.java:611)
at java.net.URL.<init>(URL.java:508)
at java.net.URL.<init>(URL.java:457)
at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:472)
at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:145)`

PHP Version: 7.0+

**Comment by NinoSkopac** [comment]
ok

**Comment by Abelkrown** [comment]
And? Just close?

**Comment by NinoSkopac** [comment]
Yeah.

**Comment by Abelkrown** [comment]
Ok. Why no resolving?

**Comment by NinoSkopac** [comment]
Because it’s easier for you to just rename the file using standard characters

**Comment by NinoSkopac** [comment]
Because it’s easier for you to just rename the file using standard characters

**Comment by Abelkrown** [comment]
Meh. Ofc it's one of the way but what to do if it is no the way?
Also it possible with temp file but it's not a good way.

**Comment by NinoSkopac** [comment]
You should always rename the uploaded file due to security reasons.
