### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by netidan** [NinoSkopac/PhpTikaWrapper#8]
TikaWrapper::getMetaData($file);
gives me regular text instead of php array.. why is that?
thanks

**Comment by NinoSkopac** [comment]
The PHPDocs do say that return is a string:

```
    /**
     * @param $filename
     * @return string
     */
    public static function getMetadata($filename){
        return self::run("--metadata", $filename);
    }
```

Feel free to create a PR with getMetaDataAsArray.
